### ISSUE TITLE
[ERROR][https://staging.site.com:/] Shell command PID 6787 returned an abnormal error code: '1'

### ISSUE THREAD

**Issue by MuhammadKhizerJaved** [maaaaz/webscreenshot#10]
[ERROR][https://staging.site.com:/] Shell command PID 6787 returned an abnormal error code: '1'
ScreenShot Somehow failed 

Getting this error whenever i run the script can't seems to find a solution ...

**Comment by maaaaz** [comment]
It gives you that error for any website or just one in particular ?

**Comment by MuhammadKhizerJaved** [comment]
Every website

**Comment by maaaaz** [comment]
try to update your phantomjs installation: https://github.com/maaaaz/webscreenshot/wiki/Phantomjs-installation

**Comment by putsi** [comment]
I'm getting this when running headless Ubuntu and fixed it with:
```
apt-get install xvfb
xvfb-run webscreenshot -i list.txt
```

**Comment by bugbaba** [comment]
I can confirm that the solution given by @putsi solves this issue.

@MuhammadKhizerJaved  could you please try this at your end too.

**Comment by maaaaz** [comment]
@putsi, interesting I never tested `webscreenshot` on an headless OS. 
I'm happy it can work after installing that `xvfb` dependency: @bugbaba, thanks for confirming it.

Best regards everyone.

**Comment by haxormad** [comment]
I was using the latest version of PhantomJS, and still getting this error! 
I had installed webscreenshot using pip!

**Comment by kd54726** [comment]
I have done the solution given by @putsi but it didn't worked. It is still giving me the same error
code : xvfb-run python webscreenshot.py -i file.txt -o ~/dir/dir/result.txt -w 20 -a "X-FORWARDED-FOR: 127.0.0.1"

so what should i do now?

**Comment by EnFinlay** [comment]
For me this was caused by incorrectly installing `phantomjs`. Solved by adding missing dependencies https://www.vultr.com/docs/how-to-install-phantomjs-on-ubuntu-16-04
