### ISSUE TITLE
Screenshot went some wrong

### ISSUE THREAD

**Issue by steffenteichmann** [maaaaz/webscreenshot#11]
Hi,
I like your tool.
But I have an error on some pages, like this:
[ERROR][https://......] Screenshot somehow failed

I think it is a problem because of an embedded youtube video

**Comment by steffenteichmann** [comment]
After using -v DEBUG it works. #don't know

**Comment by maaaaz** [comment]
Thank for your support.
If you ever any other information for debugging, feel free to post it here!
