### ISSUE TITLE
Request of feature: URL with image

### ISSUE THREAD

**Issue by jauharvp** [maaaaz/webscreenshot#13]
It would be great if you can add feature to show URL with the screenshot

**Comment by maaaaz** [comment]
Hello,

What do you mean ? Like showing the screenshot URL directly in the image ?

**Comment by jauharvp** [comment]
Yes, exactly.

When I try to add screenshot for the report, I can show the URL as well and will catch easily when we refer the screenshot.

What do you think @maaaaz ?

**Comment by MannyRamos** [comment]
I can try and work on this.

**Comment by maaaaz** [comment]
@MannyRamos, thanks that would be really nice, I'm clueless in JS/HTML/CSS.
I guess that you have to tweak the `webscreenshot.js` file with some [PhantomJS API](http://phantomjs.org/page-automation.html)

**Comment by MannyRamos** [comment]
@maaaaz I was going to try and use the PIL library on python to actually edit the photo/screenshot because python is the only language I know.

**Comment by maaaaz** [comment]
@MannyRamos. Hum I don't think that it is the good approach.
Editing the DOM by just appending the URL with a convenient font size on the top of the page and then screenshoting is the good way to do it.

**Comment by 424242424** [comment]
@maaaaz is this issue up for grabs?

**Comment by maaaaz** [comment]
@424242424 what do you mean ? if the asked feature is in progress ? unfortunately no.
I'm open to contributions :)

**Comment by 424242424** [comment]
@maaaaz I mean, can I pick it up :). If it's not in progress, do you have any thoughts on how this should be done so I could get to work on it?

**Comment by maaaaz** [comment]
@424242424 sure you can pick it up !

I imagine this feature as is:
1. First, that can only work with the `phantomjs` renderer as the other ones, without a webdriver, cannot instrument a page content

2. It should be an option, like `--show-url`, it won't be enforced by default

3. Upon a page grabbing, the URL is put inside the DOM with a proper font size and color, preferably at the top of the page, really close to the `<head>` or `<title>` tags

Cheers.

**Comment by jauharvp** [comment]
@maaaaz @424242424 I missed your comments bros.

Any luck?

**Comment by milangfx** [comment]
The easiest way is to just run a convert command to add the label:
`convert screenshot.png label:'<URL goes here>' +swap -append labeled_screenshot.png`

More options at https://imagemagick.org/Usage/annotating/

subprocess is already imported, so we can simply do a `subprocess.run(["convert", "..."])` after the screenshot is taken.

Let me know if this would work for you and I can test the feature and create a PR.

**Comment by maaaaz** [comment]
Hello @milangfx,

Really interesting, I would not have thought of using `imagemagick`.
I see multiple advantages (notably the fact that it is not correlated to the renderer, hence compatible with all) but I have some questions :
* Would it also work on Windows ? I never used `imagemagick` on Windows so I don't know: 
  * 1. If it is easy to install
  * 2. If all picture options, such as label, would be present for the Windows version
* Instead of calling directly `convert`, is there an existing Python library around `imagemagick` that supports this label option ?
  * Few [research](https://imagemagick.org/discourse-server/viewtopic.php?t=32844) points to [wand](http://docs.wand-py.org/) but I don't think the option exists

Cheers.

**Comment by maaaaz** [comment]
Nevermind, I got my answers and I implemented that feature in the version 2.7.

Use the `-l` option, after ensuring that you have `imagemagick` [installed](https://github.com/maaaaz/webscreenshot/wiki/ImageMagick-installation): another screenshot with the URL on top will be created.

Let me know if it works or not for you.

Cheers.

**Comment by milangfx** [comment]
Hello @maaaaz,

Thanks for implementing this so quickly. It works fine on my end, but I think 60 for the font size is a bit too much.

The label overhangs the screenshot when the URL is long:
![https_groups google com_443_a_python org_forum___forumsearch__with_label](https://user-images.githubusercontent.com/9085465/71772094-817e2c00-2f45-11ea-80d0-f5885611d271.png)

**Comment by maaaaz** [comment]
Thanks for your feedback !
It might be a bit big (and overhangs), but that's something I wanted to be able to quickly see the URL while browsing screenshots.

**Comment by maaaaz** [comment]
I might add user options to specify the label size and background color.

**Comment by milangfx** [comment]
Fair enough, the huge font makes it easy to read the URL at a glance.
The `-l` option could set an integer to change the font size, with a default value of 60.

**Comment by milangfx** [comment]
Thanks for adding the label options in v2.8.
I think this can be closed.

**Comment by maaaaz** [comment]
Thanks
