### ISSUE TITLE
3D maps from maps.google.com do not work

### ISSUE THREAD

**Issue by ole-tange** [maaaaz/webscreenshot#17]
`python webscreenshot.py -r chromium 'https://www.google.com.ph/maps/@55.6652884,12.4946009,89a,35y,254.22h,47.58t/data=!3m1!1e3?hl=en'` gives the loading image and not the full 3D map as you get in a browser.

**Comment by maaaaz** [comment]
Hello @ole-tange,

Thank you for that finding, I guess you're reaching the limitations of headless screenshot. 
I suppose it comes from a complex JavaScript loading and it is not related to the chosen renderer as chrome and phantomjs give also the same output.

Best regards.
