### ISSUE TITLE
Ajax actions before taking the snapshot

### ISSUE THREAD

**Issue by Tudorvr** [maaaaz/webscreenshot#18]
Would it be possible to perform an action before taking the snapshots?
For e.g. clicking a button inside the webpage to show some hidden information 

"  def lookup(driver):
    driver.get("url")
    try:
        #box = driver.wait.until(EC.presence_of_element_located((By.NAME, "q")))
        
        #button = driver.find_element_by_class_name('oc-home-search__button')
        button = driver.find_element_by_id('showPhone')
        #box.send_keys(query)
        button.click()

        image = driver.find_element_by_class_name('telnumber')
        print(image.get_attribute('element'))
        abc = driver.FindElement(By.XPath("//div[contains(@style, 'background-image'))
        #print(image.get_attribute("url"))
    
    except TimeoutException:
        print("Box or Button not found!")

**Comment by maaaaz** [comment]
Hello @Tudorvr,
From your code I understand that you need a `webdriver`: this is currently not supported.

Cheers.

**Comment by maaaaz** [comment]
cf. https://github.com/maaaaz/webscreenshot/issues/34#issuecomment-678767976
