### ISSUE TITLE
Screenshot somehow failed on some websites / Shell command abnormal code

### ISSUE THREAD

**Issue by kryogenyk** [maaaaz/webscreenshot#20]
Hey!
I am trying to use your program to download ~2k screenshots, running it for ~150 links at a time. 
For some websites it just doesn't work, saying both "Screenshot somehow failed" and "Shell command PID ---- returned abnormal error code '1' ". I ran it with xvfb, without xvfb, with -vv, without -vv.
The websites that don't work aren't consistent; if I run it now, I might get 5/31 (list with links that fail), if I run it again, I might get 4 or 6. Also, running it with -m only helps with some of the websites, still remaining a handful of them that don't work on either :443 and :80.
I have the latest PhantomJS version, I have installed webscreenshot from pip and I also cloned the repo, ran it both ways a number of times.
The network I'm connected to does not have any restrictions.
The webiste list is composed of the few thousand beggining link from Alexa top 1mil.

**Comment by maaaaz** [comment]
Hello @kryogenyk,

For a lot reasons related to PhantomJS, results might sometime not be consistent.
Could you try the latest `webscreenshot` version with different renderers (Chrome etc.) ?

Cheers.
