### ISSUE TITLE
Redirect Support / Nodejs Webpages / Additional Logging?

### ISSUE THREAD

**Issue by own3mall** [maaaaz/webscreenshot#26]
Does webscreenshot support redirects when taking screenshots?

For example, this URL generates a blank screenshot with chrome as the web driver and webscreenshot version 2.4:

https://mohaaaa.co.uk

The below URL is for a node.js powered site:

https://videos.dinofly.com

When it is screenshot, it doesn't appear to be loading all of the JavaScript / finishing the rendering as it would appear to an end user?  Any idea on this one?

Also, rather than outputting messages such as `Screenshot somehow failed`, is there a way to find out why it somehow failed?  I think it would be nice to have more info if possible.

**Comment by maaaaz** [comment]
Hello @own3mall,

I tried every renderer for your website and they all don't manage to screenshot: I can't investigate more.

Follow these indications if you want to debug: https://github.com/maaaaz/webscreenshot/issues/29#issuecomment-533876042

Cheers
