### ISSUE TITLE
Cookie parameter ignored when using chrome as engine

### ISSUE THREAD

**Issue by coldib** [maaaaz/webscreenshot#27]
Using this command does not work, as the option -c seems to be ignored:

`webscreenshot -v -r chromium --no-xserver -c COOKIE "JSESSIONID=1234; YOLO=SWAG" http://grim.at/tmp/cookie.php`

Looking in the source code it seems as if the option is only present using phantomjs - can you please fix this?

Thanks in advance!
Wolfgang

**Comment by maaaaz** [comment]
Hello,

Unfortunately I'm not aware of any cookie option for headless chrome/chromium.
But you are right that currently `webscreenshot` options are misleading, some are only available for certain renderers.

Cheers.

**Comment by maaaaz** [comment]
I just added a table mapping option supported to renderers: https://github.com/maaaaz/webscreenshot#supported-options-by-renderers
