### ISSUE TITLE
error code: 1

### ISSUE THREAD

**Issue by kd54726** [maaaaz/webscreenshot#29]
I have done the solution given by @putsi but it didn't worked. It is still giving me the same error
code : **xvfb-run python webscreenshot.py -i file.txt -o ~/dir/dir/result.txt -w 20 -a "X-FORWARDED-FOR: 127.0.0.1"**

so what should i do now?

**Comment by maaaaz** [comment]
Hello @kd54726:
1. add `-vv` option to `webscreenshot`
2. locate the `Shell command to be executed` string in the output
3. copy the executed command, try it in another terminal window and debug the renderer error
For PhantomJS, the `--debug=true` option will give you detailed messages

Cheers
