### ISSUE TITLE
OUTPUT file name

### ISSUE THREAD

**Issue by tolgatasci** [maaaaz/webscreenshot#31]
how to chaning to output file name

**Comment by maaaaz** [comment]
Hello, not possible at the moment.
What kind of options do you propose ?

**Comment by tolgatasci** [comment]
-fn filename parametre do good

**Comment by maaaaz** [comment]
As this tool process multiple input, the output filename can only be a prefix (and the suffix the dynamic part of the input), or defined with a format string.

**Comment by tolgatasci** [comment]
Yes I thought right now, bad idea. Because you're getting a list. Do as you say for the list. URL AND File name

example:
http://www.google.com filename

if blank filename default filename

if no have list -fn filename use
