### ISSUE TITLE
Crop/resize image?

### ISSUE THREAD

**Issue by clubh** [maaaaz/webscreenshot#33]
The screenshots are always the full height of the webpage.

`/usr/bin/env python3 webscreenshot.py --no-xserver -f jpg -q 80 --window-size 1600,768 blogger.com
`
I was wondering if it is possible to define the viewport?

**Comment by maaaaz** [comment]
Hello, isn't [this parameter](https://github.com/maaaaz/webscreenshot/blob/master/webscreenshot.js#L37) to do what you want according to the `phantomjs` [documentation](https://phantomjs.org/api/webpage/property/viewport-size.html) ?

**Comment by maaaaz** [comment]
Same use cases as [this PR](https://github.com/maaaaz/webscreenshot/pull/42) ?

**Comment by maaaaz** [comment]
Fixed in [v2.8](https://github.com/maaaaz/webscreenshot/commit/a3c787268dc7a3cda0b3f62f2bed1a31ea8ed5e2) and detailed [here](https://github.com/maaaaz/webscreenshot/pull/42)
