### ISSUE TITLE
renderer binary could not have been found in your current PATH environment variable.

### ISSUE THREAD

**Issue by momocr7** [maaaaz/webscreenshot#35]
when try to run webscreenshot after installing requirements,
it give me this error:
 webscreenshot.py version 2.4

[+] 4 URLs to be screenshot
[ERROR][https://173.194.67.113:443] renderer binary could not have been found in your current PATH environment variable, exiting
[ERROR][http://173.194.67.113:80] renderer binary could not have been found in your current PATH environment variable, exiting
[ERROR][https://duckduckgo.com:443/robots.txt] renderer binary could not have been found in your current PATH environment variable, exiting
[ERROR][http://google.fr:80] renderer binary could not have been found in your current PATH environment variable, exiting
[+] 4 actual URLs screenshot
[+] 0 error(s)

**Comment by maaaaz** [comment]
Hello,

Which renderer do you use ? By default it's `phantomjs` and the binary should be in the PATH.
Could you copy here the result of `$ which phantomjs` ?

**Comment by momocr7** [comment]
oh, It worked now, thank you I will close it

**Comment by ozone89** [comment]
sorry to open this, but I'm having the very same issue with 2.9, and phantomjs is in PATH

```
pi@RosterPi:~ $ which phantomjs
/usr/bin/phantomjs
```

**Comment by maaaaz** [comment]
@ozone89,
It's weird, `/usr/bin` should definitely be in the PATH.
Could you try to use that option : `--renderer-binary /usr/bin/phantomjs` ?
