### ISSUE TITLE
All ports screenshots

### ISSUE THREAD

**Issue by OSINT-d** [maaaaz/webscreenshot#38]
Is it possible to screenshot an URL is its ALL OPEN PORTS? If so, what's the command? If not...is it possible to implement it?

thx

**Comment by maaaaz** [comment]
Hello, yes it is possible if you specify in an input file one entry per line (1 line = 1 port) with the following format:
```
http(s)://domain_or_ip:port(/ressource)
domain_or_ip:port(/ressource)
domain_or_ip(/ressource)
```

**Comment by OSINT-d** [comment]
Hello,
thank you for the answer. However, I was wondering if it was possible to scan the open ports WITHOUT writing them down on a txt file.
This allows me to screenshot ports directly, without changing ports inside the file for every IP address.


VALERIA MARIA D’ONGHIA
OSINT Analyst

[cid:image001.png@01D2F192.E3E83190]



Da: Thomas D. <notifications@github.com>
Inviato: mercoledì 27 novembre 2019 18:56
A: maaaaz/webscreenshot <webscreenshot@noreply.github.com>
Cc: Valeria D'Onghia <vd@intuity.it>; Author <author@noreply.github.com>
Oggetto: Re: [maaaaz/webscreenshot] All ports screenshots (#38)


Hello, yes it is possible if you specify in an input file one entry per line (1 line = 1 port) with the following format:

http(s)://domain_or_ip:port(/ressource)

domain_or_ip:port(/ressource)

domain_or_ip(/ressource)

**Comment by maaaaz** [comment]
`webscreenshot` is not a port scanning tool and does not aim to be.
