### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'format'

### ISSUE THREAD

**Issue by TravelTrader** [maaaaz/webscreenshot#39]
This is the error code (line 361, in the craft_cmd function):

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/XUSERX/.local/lib/python3.6/site-packages/webscreenshot/webscreenshot.py", line 361, in craft_cmd
    output_format = options.format if options.renderer == 'phantomjs' else 'png'
AttributeError: 'Namespace' object has no attribute 'format'
```

Would be great if I could get it run!
Thanks for help.

**Comment by maaaaz** [comment]
Hello,

It seems that is similar to [this](https://github.com/maaaaz/webscreenshot/issues/36) and related to [that](https://github.com/maaaaz/webscreenshot/wiki/FAQ#calling-from-another-script)

Cheers.

**Comment by TravelTrader** [comment]
Thank you very much.

Now I had the same error as [this](https://github.com/maaaaz/webscreenshot/wiki/FAQ#headless-os).

My additional question is:
**How can I add the option `--no-xserver` in my Python code?**
Is there a possibility?

**Comment by maaaaz** [comment]
Glad to here that it's working for you @TravelTrader !
