### ISSUE TITLE
Window Size Configuration (either default or not) Doesn't Seem to Work 

### ISSUE THREAD

**Issue by fededamian** [maaaaz/webscreenshot#44]
Hello maaaaz, and thanks again for this great tool and the support. Today I am reporting an issue that seems pretty obvious to me, so I don't know if it happens under certain conditions in my environments, although I tested it both on Linux and Mac. Let me know if I can provide more data than the following:

- **Issue:** Output screenshots have the content of the whole page, resulting in really long images, even though the default length should be `800 px` and also when using the `--window-size` argument.
- **Tested Version:** webscreenshot 2.8 (but it happened with older versions too)
- **Tested OS:** Linux and Mac
- **Reproduction steps on Linux:** Run the following command and check the output image has more than 360 pixels on length.
```bash
python3 webscreenshot.py --no-xserver -r phantomjs -w 1 --window-size 640,360 -o ~ https://www.apple.com/mx/mac/
```
`**Reproduction steps on Mac ** Run the following command and check the output image has more than 360 pixels on length.
```bash
python3 webscreenshot.py --no-xserver -r phantomjs -w 1 --window-size 640,360 -o ~ https://www.apple.com/mx/mac/
```

**Output Image:**

![https_www apple com_443_mx_mac_](https://user-images.githubusercontent.com/19895945/72859743-a1328580-3ca3-11ea-87fa-8293e185d058.png)

**Comment by maaaaz** [comment]
Hello @fededamian,

Thanks your support !

Indeed that bug seems to be trivial:
* But I'm just using the [`viewportsize`](https://github.com/maaaaz/webscreenshot/blob/master/webscreenshot.js#L40) option in [PhantomJS](https://phantomjs.org/api/webpage/property/viewport-size.html)
* This option seems to be bugged : https://stackoverflow.com/questions/13390859/viewportsize-seems-not-to-work-with-phantomjs

Could you try with another `renderer` ?

**Comment by fededamian** [comment]
Thanks for the answer @maaaaz ,

Based on the README, I guess the other renderers have bigger issues than this one (no support for sites with invalid certs or no support for concurrency),  so I think I'll stick with phantomjs and maybe add some post-processing of the image after I grab it.

**Comment by maaaaz** [comment]
> Thanks for the answer @maaaaz ,
> 
> Based on the README, I guess the other renderers have bigger issues than this one (no support for sites with invalid certs or no support for concurrency), so I think I'll stick with phantomjs and maybe add some post-processing of the image after I grab it.


That is a good idea, I guess you can do it with `imagemagick`

**Comment by fededamian** [comment]
I was able to achieve this goal by using the following `imagemagick` command (if the output of webscreenshot is a picture with the filename `image.png`):

```bash
convert image.png -crop 640x480+0+0 +repage -background black -extent 640x480+0+0 image.png
```

Which either crops or enlarges the image to the desired resolution.

**Comment by maaaaz** [comment]
Added this issue in FAQ for reference.
