### ISSUE TITLE
workaround for 403 or Forbidden

### ISSUE THREAD

**Issue by arbazkiraak** [maaaaz/webscreenshot#47]
`https://stackoverflow.com/questions/59954122/phantomjs-page-render-blank-white-background-image-on-403`

* page.render doesn't seem to work if page returns `403 status or Forbidden`.
* Do you have any workaround in mind to get the actual screenshot of page instead of transparent or plain background image.

**Comment by maaaaz** [comment]
Hello @arbazkiraak,
I don't have a magic solution but some ideas:
* first, try another `renderer`
* second, redirect `webscreenshot` to a proxy, for instance BurpSuite, and [edit the response code](https://matthewsetter.com/introduction-to-burp-suite/) (403, to 200) to trick `phantomjs`

Cheers.

**Comment by arbazkiraak** [comment]
I don't think `second` option would be considered as a solution.

If you have a better way  to tackle the problem within the script then please do push a workaround into the current script.

**Comment by arbazkiraak** [comment]
@maaaaz ,

Any update for this?

**Comment by maaaaz** [comment]
Absolutely not

**Comment by arbazkiraak** [comment]
Can you explain to me the reason why Phantomjs exits for the status code `403`?

**Comment by maaaaz** [comment]
I really don't know, try to investigate around the `ContentOperationNotPermittedError` error.
And can you try to debug with the [Cloud](https://phantomjscloud.com/) version of PhantomJS ?
