### ISSUE TITLE
Unable to get complete url screenshot

### ISSUE THREAD

**Issue by sarath4** [maaaaz/webscreenshot#49]
Unable to get complete url screenshot

**Comment by maaaaz** [comment]
More details maybe ?

**Comment by sarath4** [comment]
<img width="320" alt="jboss" src="https://user-images.githubusercontent.com/41371083/75838653-80099c80-5dec-11ea-8d5e-b9d25da73f8b.png">
I have attached an image, like am trying to access the image. But it shows only the image not with the url (Complete screenshot with the url what we are trying to access)

**Comment by maaaaz** [comment]
I'm sorry but I don't understand.
You want a screenshot with the URL displayed inside ? Use the `--label` option.

**Comment by sarath4** [comment]
when i run the command am unable to find the screenshot with url with the output like below.
![image](https://user-images.githubusercontent.com/41371083/76042039-b294d000-5f79-11ea-86c9-0d8b9af131b6.png)

**Comment by sarath4** [comment]
When i run the command i can see only the way is like below. Here there was no url
![image](https://user-images.githubusercontent.com/41371083/76042079-cdffdb00-5f79-11ea-9dca-e6fd30e24254.png)

**Comment by maaaaz** [comment]
Ahh you mean that the URL/address bar is not shown ? Wow it took me a lot of time to understand !

It seems that neither [phantomjs](https://github.com/brenden/node-webshot/issues/179) nor [`chrome headless`](https://stackoverflow.com/questions/59519681/how-to-take-an-address-bar-when-using-chrome-chromium-headless-mode) can show the bar.
But still you can use the `--label` option of `webscreenshot`.

**Comment by sarath4** [comment]
Can you please help with the complete option How to get the url.

Example  multiple urls:
1. https://www.google.com
2. https://www.facebook.com

Can you please provide the full command how to run and get the output with url/address also.

**Comment by sarath4** [comment]
Can you please help me with the complete command withe label option.

**Comment by maaaaz** [comment]
`$ webscreenshot google.com --label`

**Comment by sarath4** [comment]
am getting below error.
C:\>D:\python\python C:\Users\kumaalla\Downloads\webscreenshot-master\webscreenshot-master\webscreenshot.py www.google.com --label
webscreenshot.py version 2.9

[+] 1 URLs to be screenshot
[ERROR][http://www.google.com:80] Shell command PID 17960 returned an abnormal error code: '4'
[ERROR][http://www.google.com:80] Screenshot somehow failed

[+] 1 actual URLs screenshot
[+] 0 error(s)

**Comment by maaaaz** [comment]
https://github.com/maaaaz/webscreenshot/wiki/ImageMagick-installation

**Comment by sarath4** [comment]
HI This time command was successful but the URL/address bar is not shown ? 

D:\python\python C:\Users\kumar\Downloads\webscreenshot-master\webscreenshot-master\webscreenshot.py www.google.com --label --imagemagick-binary C:\Users\kumar\Downloads\imagemagic
webscreenshot.py version 2.9

[+] 1 URLs to be screenshot
[+] 1 actual URLs screenshot
[+] 0 error(s)
![image](https://user-images.githubusercontent.com/41371083/77642995-9b4b7000-6f84-11ea-8301-6b9c40eae9b8.png)

**Comment by maaaaz** [comment]
Great !
It seems that something went wrong after the capture, before imagemagick converting the image to add the URL.
Can you try again with the `--v` option to have a verbose output ?
