### ISSUE TITLE
error renderer binary could not have been found in your current PATH environment variable, exiting

### ISSUE THREAD

**Issue by abdalla0x01** [maaaaz/webscreenshot#50]
I am having some problems when using the tool

- error:
`
 [ERROR][http://website:port] renderer binary could not have been found in your current PATH environment variable, exiting
`

**Comment by maaaaz** [comment]
Hello @abdalla0x01,
Which renderer do you ? Have you followed [this](https://github.com/maaaaz/webscreenshot/wiki/PhantomJS-installation)

Could you try with another renderer (chrome, chromium) ?

**Comment by abdalla0x01** [comment]
**Thank you my friend the problem was solved** 
The package was installed with the following command: 
`apt-get update && apt-get install phantomjs`
### Thank you
