### ISSUE TITLE
Enhancement: Functionality to get a result of error url list

### ISSUE THREAD

**Issue by g33kyshivam** [maaaaz/webscreenshot#54]
It would be good to have a feature to get those failed screenshot URL list to run over those manually or by another tool.

**Comment by maaaaz** [comment]
Hello @g33kyshivam,

Indeed, I'll think about it.

**Comment by maaaaz** [comment]
Feature added in v2.93, it generates by default a `webscreenshots_failed.txt` file.
Add the `--no-error-file` option to disable this feature.
