### ISSUE TITLE
Webscreenshot.py making a weird screenshot (used within different python script)

### ISSUE THREAD

**Issue by jefferu** [maaaaz/webscreenshot#56]
Hi currently im using the take_screenshot function from another python script. Using python 3.6 on Ubuntu

`options = argparse.Namespace(URL=None, ajax_max_timeouts='1400,1800', cookie=None, crop=None, format='png',
                                         header=None, http_password=None, http_username=None, imagemagick_binary=None,
                                         input_file=None, label=False, log_level='DEBUG', multiprotocol=False,
                                         no_xserver=True,
                                         output_directory=path, port=None, proxy=None, proxy_auth=None,
                                         proxy_type=None, quality=75, renderer='phantomjs', renderer_binary=None,
                                         ssl=False,
                                         timeout=30, verbosity=2, window_size='1200,800', workers=4)  -> take_screenshot(url_container, options)`

the url container just contains a bunch of urls. 

The output which gets generated on a specific page which I want to monitor looks like this
![balken](https://user-images.githubusercontent.com/9824749/91548879-64f49100-e926-11ea-85f4-6728821179a6.png)

**but it should look more like this**
![balken 2](https://user-images.githubusercontent.com/9824749/91548925-750c7080-e926-11ea-9943-9188ecf5ccef.png)

why does this happen?

**Comment by maaaaz** [comment]
Hello,

Absolutely no idea but you can try to:
1. With phantomjs, [adjust timeouts](https://github.com/maaaaz/webscreenshot/wiki/FAQ#screenshot-taken-before-the-page-is-totally-loaded)
2. Change the renderer, using `chrome` for instance

Cheers.

**Comment by jefferu** [comment]
**2. Change the renderer, using `chrome` for instance**

how exactly do I accomplish that?

**Comment by maaaaz** [comment]
1. Install Chrome on your system
2. Launch webscreenshot specifying `-r chrome` and `--renderer-binary /path/to/the/chrome/executable`

**Comment by jefferu** [comment]
do i have to change/edit any other parameters as shown above? Is it only the path to the renderer binary and the renderer?

**Comment by maaaaz** [comment]
> "Is it only the path to the renderer binary and the renderer"

Yes 

Choosing a renderer is always an available option. But, some advanced options for processing are not available for each renderer.
