### ISSUE TITLE
Some lazy-rendering question.

### ISSUE THREAD

**Issue by tesths** [maaaaz/webscreenshot#6]
When I use the webscreenshot to screenshot http://mp.weixin.qq.com/s/AZa0at-yu0oVyzCGtsrPIQ.
I found some of the image become grey with progress.
Is there any solution?

**Comment by maaaaz** [comment]
Hello,

It seems to be related with the fact that you need to scroll to load those images.
I quickly tried some methods from [here](http://stackoverflow.com/questions/31963804/how-to-scroll-in-phantomjs-to-trigger-lazy-loads), [here](http://stackoverflow.com/questions/16561582/how-to-scroll-down-with-phantomjs-to-load-dynamic-content) and [here](https://github.com/ariya/phantomjs/issues/14811) but haven't found a proper way.

Good luck with that :)

Cheers.

**Comment by tesths** [comment]
Ok! Thanks for your help! I will try!
