### ISSUE TITLE
No X server has been found and the xvfb-run binary could not be found, please install xvfb on your system

### ISSUE THREAD

**Issue by DukeNgn** [maaaaz/webscreenshot#70]
### Issue
I got an error when trying to run something simple just as `webscreenshot -v google.fr`

The error is:

```
❯ webscreenshot -v google.fr
webscreenshot.py version 2.94

[INFO][General] 'google.fr' has been formatted as 'http://google.fr:80' with supplied overriding options
[+] 1 URLs to be screenshot
[ERROR][http://google.fr:80] No X server has been found and the xvfb-run binary could not be found, please install xvfb on your system
[+] 0 actual URLs screenshot
[+] 1 error(s)
    http://google.fr:80
```

I verified that `xvfb` was installed on my system by doing:
```
❯ xvfb -help
use: X [:<display>] [option]
-a #                   default pointer acceleration (factor)
-ac                    disable access control restrictions
-audit int             set audit trail level
-auth file             select authorization file
-br                    create root window with black background
+bs                    enable any backing store support
-bs                    disable any backing store support
-c                     turns off key-click
c #                    key-click volume (0-100)
....
```

I'm running the python script inside a virtual environment.
How should I fix this?

### More information:
OS: MacOS Catalina

**Comment by maaaaz** [comment]
Hello,
`webscreenshot` without an X server looks for `xvfb-run` https://github.com/maaaaz/webscreenshot/blob/16e5c2a7448a9cb3248074de287c30a86c6974b6/webscreenshot.py#L109

I don't know MacOS and I never tried `webscreenshot` on it.

You need to find a way to have [`xvfb-run`](https://stackoverflow.com/questions/25451133/xvfb-run-on-os-x) on your system.
