### ISSUE TITLE
i cant take screenshot

### ISSUE THREAD

**Issue by zicohip** [maaaaz/webscreenshot#78]
the tool : 
![image](https://user-images.githubusercontent.com/76248189/159188853-ec30bf1f-161a-4408-9f15-3b220e7323a4.png)

when go to folder is empty

![image](https://user-images.githubusercontent.com/76248189/159188887-4230e278-d723-42b9-835c-ff5ccd9cc133.png)

the `phantomjs`

![image](https://user-images.githubusercontent.com/76248189/159189006-2bbbc720-eab3-452b-9d3e-cd46e7d9e7d9.png)

**Comment by moolakarapasanga** [comment]
I am also got the same error.

**Comment by maaaaz** [comment]
You need PhantomJS v2 minimum 
https://github.com/maaaaz/webscreenshot/wiki/FAQ#ssltls-errors-in-old-phantomjs-versions
